### PR TITLE
Feat screenshot html

### PR DESCRIPTION
**Pull request by bugrakocabay**
As requested [here](https://github.com/projectdiscovery/httpx/issues/1208), I have implemented a feature for -screenshot flag, which saves the result screenshots in an indexed html file as this;

image

The basic functionality is ready, but there is still room for improvement. Open for any suggestions.

- [x] Populate Response Info field with given flags, such as status code, IP, Title etc.

### CODE REVIEW

**Comment by bugrakocabay** [comment]
Populated response info column with the flags provided by user
image

review please

**Review by Mzack9999 — CHANGES_REQUESTED** [review]
@bugrakocabay This is a very cool feature! What do you think about moving the html code into an external html template that can be populated with template syntax (either [go native](https://gowebexamples.com/templates/) or something like [twig like syntax](https://github.com/Masterminds/sprig))? In this way the output report would be completely customizable

**Comment by bugrakocabay** [comment]
Spinned up a new goroutine with a channel, as when I used it inside the one above it, some race conditions occurred.

**Review by Mzack9999 — APPROVED** [review]
lgtm!
image

**Review by ehsandeep — APPROVED** [review]
thank you @bugrakocabay for adding this support.

**Pull request merged**
