### PR TITLE
Update title.go

### PR DESCRIPTION
**Pull request by bimkos**
Fix broken 
eg
<title&gt;

### CODE REVIEW

**Comment by bimkos** [comment]
`<title&gt;Westway Aircraft Models</title&gt; <meta http-equiv=&#34;Content-Language&#34; content=&#34;en&#34;&gt; <meta name=&#34;description&#34; content=&#34;Aircraft display models,travel agent models, aviation models new and old.&#34;&gt; <meta name=&#34;keywords&#34; content=&#34;aircraft models, travel agent aircraft, aviation models, display resin, airplane models, air, military airplanes, commercial airplanes, general aviation, cutaway aircraft, westway, aviation, fibreglass models, plastic models, aviation aircraft, boac aircraft, made to order aircraft, aviation free ads, scale,1/100,1/72,1/50,1/36,1/25,jet aircraft, old aviation aircraft, new aviation, jet aircraft, proped aircraft, concorde planes, boeing, airbus, VC10 aircraft, british airway, desk top, floor standing aircraft, pacmin, space models, ami&#34;&gt;"><title>Home Page - Westway Aircraft models</title>`

**Comment by Mzack9999** [comment]
@bimkos - Thanks for your PR! I used the existing regex as I encountered a few cases where the page title was malformed (eg `<title >xxx</title>` and this one worked as a sort of catch-all (still prone to errors indeed, like the edge case reported here). Anyway HTML specifications indeed requires the `title` tag to works as you implemented. What do you think about adding support for a limited set of characters (eg space) between the end of the word (eg `space`) and the symbols `<>`?

**Comment by bimkos** [comment]
Because of such examples, scanning breaks =) One of the options is to put a _try_ construct in the code.  I also think to review the regex, I think I can make it respond only to spaces.

**Comment by bimkos** [comment]
@Mzack9999 Do you have groups in Telegram or Discord? Or maybe KeyBase?

**Comment by bauthard** [comment]
@bimkos we do have discord server, you can join at https://discord.com/invite/KECAGdH

**Pull request merged**
