### PR TITLE
Error page classifier

### LINKED ISSUE #1201: Add onboard hash / classic ML classifier for standard error-pages/home-pages
### Please describe your feature request:
`httpx` should be able to add within the output heuristic guess if the page is an error-page/home-page of the most common web frameworks. This requires some investigation. Some potential approaches are the following:
- Perceptual hash of error pages with threshold
- simhash comparison with pre-calculated ones from most common web apps
- Bayesian classifier
- SVM

Some analysis might be performed, taking advantage of the screenshot taken if the headless modality is used.

### PR DESCRIPTION
**Pull request by dogancanbakir**
This PR adds an error page classifier and error page filtering support. Closes #1201.

w/o filtering:
```
$ go run httpx.go -l list.txt

    __    __  __       _  __
   / /_  / /_/ /_____ | |/ /
  / __ \/ __/ __/ __ \|   /
 / / / / /_/ /_/ /_/ /   |
/_/ /_/\__/\__/ .___/_/|_|
             /_/

                projectdiscovery.io

[INF] Current httpx version v1.3.2 (latest)
https://projectdiscovery.io/notarealpage
https://projectdiscovery.io
https://scanme.sh
```

w/ filtering:

```
$ go run httpx.go -l list.txt -fep

    __    __  __       _  __
   / /_  / /_/ /_____ | |/ /
  / __ \/ __/ __/ __ \|   /
 / / / / /_/ /_/ /_/ /   |
/_/ /_/\__/\__/ .___/_/|_|
             /_/

                projectdiscovery.io

[INF] Current httpx version v1.3.2 (latest)
https://projectdiscovery.io
https://scanme.sh
```

```
$ cat list.txt 
https://projectdiscovery.io
https://projectdiscovery.io/notarealpage
http://scanme.sh
```

### CODE REVIEW

**Review by Mzack9999 — APPROVED** [review]
lgtm - commented out training logic to reduce embed occupation. We will need to move it the utils repository and automate periodic training via GH action

**Review by ehsandeep — CHANGES_REQUESTED** [review]
@dogancanbakir This is an interesting feature, can you add a small document about what this feature means to the user and its working as well when best to use?

Also, we can write information to `filtered_error_page.json` of what is being filtered when `-fep` option is used for further review/testing.

**Review by Mzack9999 — CHANGES_REQUESTED** [review]
- [x] Merge conflict
- [ ] Let's check if we can move the bayesian classifier agnostic implementation to `utils/mlutils` and keep here only the loading with weights (with commented out code)
- [ ] Optional: unless we are going to implement a periodic scrape + train GH action for now I think static stored weights from our latest training suffice

**Comment by dogancanbakir** [comment]
@Mzack9999, 

>  Let's check if we can move the bayesian classifier agnostic implementation to utils/mlutils and keep here only the loading with weights (with commented out code)

I have submitted a PR (https://github.com/projectdiscovery/utils/pull/208) which, once merged, can be utilized in this implementation.

> Optional: unless we are going to implement a periodic scrape + train GH action for now I think static stored weights from our latest training suffice

I think we can do the latter; using stored weights from our latest training is fine.

**Review by Mzack9999 — CHANGES_REQUESTED** [review]
Let's cleanup the code and reuse https://github.com/projectdiscovery/utils/pull/208 (merged)

**Review by Mzack9999 — APPROVED** [review]

**Pull request merged**
