### PR TITLE
fix windows path issue

### LINKED ISSUE #1421: The relative position of the image path does not render properly on html
### httpx version:
v1.3.6

### Current Behavior:

Displaying images
### Expected Behavior:

The image cannot be displayed.
### Steps To Reproduce:

```
httpx -l 1.txt -ss
```
image

### PR DESCRIPTION
**Pull request by dogancanbakir**
Closes #1421.

Note: It still needs to be tested. However, I am setting up a Windows test environment on AWS. I'll make sure to follow up with you once testing is complete.

### CODE REVIEW

**Comment by dogancanbakir** [comment]
@enomothem,
In the meantime, can you retest with this branch `fix_windows_path_issue`? Thanks!

**Comment by enomothem** [comment]
@dogancanbakir  Yes, I did not solve the problem after compiling this branch
image
image

**Comment by enomothem** [comment]
I committed a branch that solved the problem, screenshot below https://github.com/projectdiscovery/httpx/pull/1437/commits/5fd1f84c5770218f44266e80eab4c0ebe608a1a5

image

**Comment by dogancanbakir** [comment]
@enomothem, Made the changes! Thanks for the help!

**Review by tarunKoyalwar — APPROVED** [review]
LGTM !

**Review by ehsandeep — APPROVED** [review]

**Pull request merged**
