### PR TITLE
Add default port for URL to solve automatic use of HTTP

### PR DESCRIPTION
**Pull request by Becivells**
## The results are as expected

```shell
echo "www.baidu.com"|httpx   -title -content-length -status-code #auto use https
https://www.baidu.com [302] [161] [302 Found]
```

```
echo "http://www.baidu.com:80"|httpx   -title -content-length -status-code #use  http
http://www.baidu.com:80 [200] [300813] [百度一下，你就知道]
```

## Results did not meet expectations

```shell
echo "http://www.baidu.com"|httpx   -title -content-length -status-code #auto jump https
https://www.baidu.com [302] [161] [302 Found]
```

## Modified program

```
echo "http://www.baidu.com"|httpx   -title -content-length -status-code #use http
http://www.baidu.com:80 [200] [300813] [百度一下，你就知道]
```

### CODE REVIEW

**Comment by ehsandeep** [comment]
@Becivells Can you specify what version of **httpx** are you running as below example works fine for me, I'm on httpx v1.0.6

```
echo http://www.baidu.com | httpx  -title -content-length -status-code -silent
http://www.baidu.com [200] [262] []
```

**Comment by Becivells** [comment]
I just downloaded the latest version. The problem still exists.
result is https not http
```shell
httpx -version
[INF] Current Version: v1.0.6
```


```shell
echo "http://www.baidu.com"|httpx   -title -content-length -status-code
https://www.baidu.com [200] [227] []
```

```shell
echo "http://www.baidu.com:80"|httpx   -title -content-length -status-code
http://www.baidu.com:80 [200] [300823] [百度一下，你就知道]
```

**Comment by ehsandeep** [comment]
@Becivells Hey, it took some time to understand the issue, basically attempting to connect on HTTPS is the default behavior by design, if you want another way around, you can do it using **ports** flag.

```
echo http://www.baidu.com | ./httpx -silent -status-code -title -ports 80
http://www.baidu.com:80 [200] [百度一下，你就知道]
```

You can also define scheme custom HTTP schema for ports if you want, `-ports http:80,https:443,http:8443`, if this solves your problem we can close this PR.

**Comment by Becivells** [comment]
Maybe I didn't describe it clearly. It's fine to automatically use https when the url is an IP address or domain name. But when I use http it already implies that I am using port 80. The `custom HTTP schema` has changed these behaviors, and when I have many URLs I have to sort out the ports and add them to the `custom HTTP schema`.

Example:

```
echo "http://1.33.170.246:8000"
http://1.33.170.246:8000 [401 Authorization Required]
```

```
echo "http://1.33.170.246:8000"|httpx -ports http:80,https:443 -title
http://1.33.170.246:80 []
```

In the process of penetration testing I found that the same IP address port 80 and port 443 may not correspond to the same website

**Comment by ehsandeep** [comment]
```bash
# Current behavior in case no HTTP scheme
$ echo hackerone.com | httpx -silent
https://hackerone.com

# Current behavior with HTTP scheme
$ echo http://hackerone.com | httpx -silent
https://hackerone.com

# Updated behavior in case no HTTP scheme
$ echo hackerone.com | ./httpx -silent
https://hackerone.com

# Updated behavior with HTTP scheme
$ echo http://hackerone.com | ./httpx -silent
http://hackerone.com
```

This change will respect the user's input HTTP scheme if provided and will default to HTTPS as before in case of no HTTP scheme is provided as input.

Please correct me if I misunderstood something @Becivells.

**Comment by Becivells** [comment]
Yes. Thank you for your patience.

**Review by Ice3man543 — APPROVED** [review]
The PR looks good to me! Merging now!

**Comment by ehsandeep** [comment]
@Becivells just to confirm, when you have `http://` or `https://` in the input, this PR print the input schema, but still makes both HTTP/HTTPS request instead of one which is requested in the input, is it expected?

For example:-

If you build httpx with dev since this PR is merged, the below example still makes both HTTP and HTTP requests.

```
echo http://engage.tesla.com | httpx -silent
```

image

**Comment by Becivells** [comment]
yes. According to the rules of httpx, it is like this

this is example **Be careful this is a honey pot**
```
# curl -k https://ivansotof.com:80|more
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  1 30737    1   528    0     0   1227      0  0:00:25 --:--:--  0:00:25  1225
<!DOCTYPE html>
<html>
	<head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta http-equiv="Pragma" content="no-cache" />
        <meta http-equiv="refresh" content="0;url=/xd/ellehoxox/spider">
        <title>IntelOwl</title>
	</head>
<body>
<p hidden="hidden">
<!--
<a href="jpg.html">LIVE JPEG</a><br>
<a href="liveie.html">Internet Monitor (Microsoft Internet Explorer 8, 9, 10, 11) </a><br>
<a href="DVRRemoteAP.exe">Download 32 bits DVR Client (Windows 7, Windows 8, Windows 10)</a><br>
<a href="DVRRemoteAP_X64.exe">Download 64 bits DVR Client (Windows 7, Windows 8, Windows 10)</a><br>
<a href="DVFPlayer.zip">Download 32/64 bits File Player (Windows 7, Windows 8, Windows 10)</a><br>
<?xml version="1.0" encoding="utf-8"?><base64Binary xmlns="http://micros-hosting.com/EGateway/">
Location: /admin
<meta name="generator" content="vBulletin 5.5.4" />
Location: /ui/login

Model=AC1450
Firmware=V1.0.0.36_10.0.17
100 30737  100 30737    0     0  54887      0 --:--:-- --:--:-- --:--:-- 54789
"exceptionMessageValue":"javax.servlet.ServletException: No valid forensics analysis solrDocIds parameter found."
Content-Disposition
.
.
.
.
```

```
# echo "ivansotof.com:80"|httpx

    __    __  __       _  __
   / /_  / /_/ /_____ | |/ /
  / __ \/ __/ __/ __ \|   /
 / / / / /_/ /_/ /_/ /   |
/_/ /_/\__/\__/ .___/_/|_|
             /_/              v1.0.6

		projectdiscovery.io

Use with caution. You are responsible for your actions
Developers assume no liability and are not responsible for any misuse or damage.
https://ivansotof.com:80
```

**Comment by ehsandeep** [comment]
Hi @Becivells, we updated this support and made it optional as it was creating confusion between how httpx was getting used  vs new behavior as default, so now this should be supported with `-no-fallback-scheme` flag.

**Comment by Becivells** [comment]
ok

**Pull request merged**
