### PR TITLE
Feature: optional flag to skip a host if it has a private IP address.

### PR DESCRIPTION
**Pull request by CodyCline**
Implements feature request outlined in #1407.

### CODE REVIEW

**Review by dogancanbakir — APPROVED** [review]
LGTM
```console
$ go run . -u localhost,scanme.sh -eph -debug

    __    __  __       _  __
   / /_  / /_/ /_____ | |/ /
  / __ \/ __/ __/ __ \|   /
 / / / / /_/ /_/ /_/ /   |
/_/ /_/\__/\__/ .___/_/|_|
             /_/

                projectdiscovery.io

[INF] Current httpx version v1.3.6 (latest)
[DBG] Skipping private host localhost
[DBG] Failed 'localhost': target has a private ip and will only connect within same local network
[INF] Dumped HTTP request for https://scanme.sh

GET / HTTP/1.1
Host: scanme.sh
User-Agent: Mozilla/5.0 (compatible; YandexNews/4.0; +http://yandex.com/bots)
Accept-Charset: utf-8
Accept-Encoding: gzip

[INF] Dumped HTTP response for https://scanme.sh

HTTP/1.1 200 OK
Connection: close
Content-Length: 2
Content-Type: text/plain; charset=utf-8
Date: Thu, 19 Oct 2023 11:19:45 GMT

ok
https://scanme.sh
```

**Review by ehsandeep — CHANGES_REQUESTED** [review]
Thank you for the PR @CodyCline, it works fine without port input, but it still passthrough when a port is specified in input or via port option.

```console
./httpx -u localhost -sc -title -p 8080 -eph

    __    __  __       _  __
   / /_  / /_/ /_____ | |/ /
  / __ \/ __/ __/ __ \|   /
 / / / / /_/ /_/ /_/ /   |
/_/ /_/\__/\__/ .___/_/|_|
             /_/

		projectdiscovery.io

[INF] Current httpx version v1.3.5 (latest)
http://localhost:8080 [200] [Burp Suite Professional]
~/Github/httpx $ ./httpx -u localhost -sc -title -p 8080 -eph

    __    __  __       _  __
   / /_  / /_/ /_____ | |/ /
  / __ \/ __/ __/ __ \|   /
 / / / / /_/ /_/ /_/ /   |
/_/ /_/\__/\__/ .___/_/|_|
             /_/

		projectdiscovery.io

[INF] Current httpx version v1.3.5 (latest)
http://localhost:8080 [200] [Burp Suite Professional]
```

**Comment by CodyCline** [comment]
@ehsandeep nice catch! This happens because I was passing `URL.Host` instead of `URL.Hostname()` into the `skipPrivateHosts` function. The latter option strips out the port number from the host before calling the DNS lookup. Fix committed now.

**Review by ehsandeep — APPROVED** [review]
Build fails is known and unrelated to this PR.

**Comment by CodyCline** [comment]
> Build fails is known and unrelated to this PR.

Thanks for clarifying.

**Pull request merged**
