### PR TITLE
enable leakless

### LINKED ISSUE #1425: Excessive Zombie Processes and 'Failed to Create New OS Thread' Error in httpx Screenshot Utility
### Current Behavior:
Not able to create new httpx task

## Description:
On using httpx's screenshot function to get website images in bulk, the process generates a lot of zombie processes, and after a large number of zombie processes have appeared, I can no longer create the httpx task, and report an error: **runtime: failed to create new OS thread (have 19 already; errno=11)**
image

### Steps To Reproduce:

Full command: `httpx -title -duc -tech-detect -no-stdin -status-code -fr -nf -json -ss -u http://example.com/`

OS Version: `Linux 1b10610f65fd 6.1.0-kali5-amd64 https://github.com/projectdiscovery/httpx/pull/1 SMP PREEMPT_DYNAMIC 
Debian 6.1.12-1kali2 (2023-02-23) x86_64 GNU/Linux`

### Anything else:
discussed at: https://github.com/projectdiscovery/httpx/discussions/1415#discussioncomment-7441894

### PR DESCRIPTION
**Pull request by dogancanbakir**
Closes #1425.

### CODE REVIEW

**Comment by dogancanbakir** [comment]
Hey @monitor403, could you please try the change on branch `enable_leakless`?  Let me know how it goes.

**Review by Mzack9999 — CHANGES_REQUESTED** [review]
let's comment out the code related to killing pids and ensure leakless doesn't prevent httpx from running (GH actions are all green so I think we are good)

**Review by Mzack9999 — APPROVED** [review]

**Comment by Mzack9999** [comment]
Runs fine on linux and osx - On Win depends if Windows Defender thinks it's a world-ending virus

**Comment by monitor403** [comment]
> let's comment out the code related to killing pids and ensure leakless doesn't prevent httpx from running (GH actions are all green so I think we are good)

Glad to see you guys took care of the problem, but my own compilation to run on linux still seems to give me zombie processes。
Reproduction steps:
1. Environment: Linux 6fa4957cbf42 6.1.0-kali5-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.12-1kali2 (2023-02-23) x86_64 GNU/Linux
2. Command: httpx -title -duc -tech-detect -no-stdin -status-code -fr -nf -json -ss -u http://example.com.
image
Best wishes.

**Comment by monitor403** [comment]
> Hey @monitor403, could you please try the change on branch `enable_leakless`? Let me know how it goes.

ok,i will try to read httpx code and make pr

**Review by ehsandeep — APPROVED** [review]

**Pull request merged**
