### PR TITLE
Extract `body_domains` and` body_fqdns` to jsonl

### PR DESCRIPTION
**Pull request by RamanaReddy0M**
- closes: #1728

### CODE REVIEW

**Comment by RamanaReddy0M** [comment]
```console
✗ echo hackerone.com | go run . -fr -efqdn -j -silent | jq
{
  "timestamp": "2024-06-05T13:19:59.752485+05:30",
  ...
  "resolvers": [
    "1.1.1.1:53",
    "1.0.0.1:53"
  ],
  "body_fqdn": [
    "www.instagram.com",
    "www.linkedin.com",
    "www.twitter.com",
    "www.facebook.com",
    "docs.hackerone.com",
    "www.w3.org",
    "consent.trustarc.com",
    "www.drupal.org",
    "www.googletagmanager.com",
    "cdn.optimizely.com",
    "www.youtube.com",
    "www.hackeronestatus.com",
    "www.hackerone.com",
    "js-agent.newrelic.com"
  ],
  "body_domains": [
    "rdfs.org",
    "instagram.com",
    "ogp.me",
    "fonts.googleapis.com",
    "purl.org",
    "drupal.org",
    "hackeronestatus.com",
    "linkedin.com",
    "googletagmanager.com",
    "schema.org",
    "custom.transaction",
    "hackerone.com",
    "w3.org",
    "h1.community",
    "optimizely.com",
    "facebook.com",
    "trustarc.com",
    "youtube.com",
    "xmlns.com",
    "twitter.com",
    "newrelic.com"
  ]
}
```

**Review by ehsandeep — CHANGES_REQUESTED** [review]
- [x] parsing issue as fqdn / domain includes port.

```
echo https://staging-airtableblocks.com | ./httpx -efqdn -j | jq .
```

we can include test for `fqdn` and `domain` parsing.

**Review by ehsandeep — CHANGES_REQUESTED** [review]
```console
 $ echo iotex.io | ./httpx -j -efqdn -silent  | jq .
{
  "timestamp": "2024-06-13T02:52:21.666917+05:30",
  "cdn_name": "cloudflare",
  "port": "443",
  "url": "https://iotex.io",
  "input": "iotex.io",
  "title": "IoTeX - DePIN’s Modular Platform",
  "scheme": "https",
  "webserver": "cloudflare",
  "content_type": "text/html",
  "method": "GET",
  "host": "104.26.2.250",
  "path": "/",
  "time": "196.960333ms",
  "a": [
    "104.26.3.250",
    "104.26.2.250",
    "172.67.72.48"
  ],
  "aaaa": [
    "2606:4700:20::ac43:4830",
    "2606:4700:20::681a:3fa",
    "2606:4700:20::681a:2fa"
  ],
  "tech": [
    "Cloudflare",
    "HSTS",
    "HTTP/3"
  ],
  "words": 29080,
  "lines": 50,
  "status_code": 200,
  "content_length": 892404,
  "failed": false,
  "cdn": true,
  "knowledgebase": {
    "PageType": "nonerror",
    "pHash": 0
  },
  "resolvers": [
    "100.95.0.252:53",
    "100.95.0.253:53"
  ],
  "body_fqdn": [
    "iotex.b-cdn.net",
    "www.youtube.com",
    "framer-sites.b-cdn.net/images/3doszlzrsjqnaceotlhmk5dqmm.gif);background-size:cover;background-repeat:no-repeat;background-position:0%",
    "docs.iotex.io",
    "ecosystem.iotex.io",
    "events.framer.com",
    "framer-sites.b-cdn.net",
    "www.w3.org"
  ],
  "body_domains": [
    "youtube.com",
    "twitter.com",
    "framer.com",
    "b-cdn.net",
    "w3.org",
    "depinscan.io",
    "net/images/3doszlzrsjqnaceotlhmk5dqmm.gif);background-size:cover;background-repeat:no-repeat;background-position:0%",
    "discord.com",
    "iotex.io"
  ]
}
```



domain list from https://github.com/projectdiscovery/public-bugbounty-programs/blob/main/chaos-bugbounty-list.json can be used for testing.

**Review by ehsandeep — CHANGES_REQUESTED** [review]
```console
 echo zapier.com | ./httpx -efqdn -j | jq .
 ```
 
@RamanaReddy0M we can use the list to confirm if this feature is working as expected.###

**Review by ehsandeep — APPROVED** [review]

**Comment by tarunKoyalwar** [comment]
## New changes

- misc updates to regex + more logic to reduce fp and capturing javascript variables / strings

### Before
```console
$ echo hackerone.com | ./httpx -fr -efqdn -j | jq -r '.body_domains'

    __    __  __       _  __
   / /_  / /_/ /_____ | |/ /
  / __ \/ __/ __/ __ \|   /
 / / / / /_/ /_/ /_/ /   |
/_/ /_/\__/\__/ .___/_/|_|
             /_/

		projectdiscovery.io

[INF] Current httpx version v1.6.3 (latest)
[
  "nreum.info",
  "e.exposed",
  "xmlns.com",
  "t.host",
  "fonts.googleapis.com",
  "r.target",
  "drupal.org",
  "d.ee",
  "e.info",
  "h1.community",
  "enduser.id",
  "nr-data.net",
  "input.search",
  "hackeronestatus.com",
  "twitter.com",
  "marketo.com",
  "d.tk",
  "syntaxerror.name",
  "this.name",
  "performance.now",
  "r.info",
  "this.auto",
  "a.call",
  "i.il",
  "d.spa",
  "t.name",
  "f.il",
  "r.nc",
  "ogp.me",
  "facebook.com",
  "n.spa",
  "u.il",
  "i.nc",
  "this.info",
  "params.cat",
  "rdfs.org",
  "linkedin.com",
  "o.info",
  "r.ky",
  "schema.org",
  "n.call",
  "y.data",
  "this.run",
  "t.search",
  "optimizely.com",
  "youtube.com",
  "purl.org",
  "gstatic.com",
  "s.name",
  "hackerone.com",
  "instagram.com",
  "googletagmanager.com",
  "newrelic.com",
  "this.ee",
  "this.target",
  "hasownproperty.call",
  "p.il",
  "r.ee",
  "n.ee",
  "e.name",
  "w3.org",
  "n.host",
  "trustarc.com",
  "date.now"
]

```

### Now
```console
$ echo hackerone.com | ./httpx -fr -efqdn -j | jq -r '.body_domains'

    __    __  __       _  __
   / /_  / /_/ /_____ | |/ /
  / __ \/ __/ __/ __ \|   /
 / / / / /_/ /_/ /_/ /   |
/_/ /_/\__/\__/ .___/_/|_|
             /_/

		projectdiscovery.io

[INF] Current httpx version v1.6.3 (latest)
[
  "newrelic.com",
  "fonts.googleapis.com",
  "linkedin.com",
  "marketo.com",
  "input.search",
  "schema.org",
  "xmlns.com",
  "ogp.me",
  "rdfs.org",
  "nr-data.net",
  "optimizely.com",
  "trustarc.com",
  "gstatic.com",
  "purl.org",
  "hackeronestatus.com",
  "facebook.com",
  "twitter.com",
  "instagram.com",
  "h1.community",
  "youtube.com",
  "googletagmanager.com",
  "enduser.id",
  "w3.org"
]
```

**Review by ehsandeep — APPROVED** [review]

**Pull request merged**
