### PR TITLE
Proxy desc

### PR DESCRIPTION
**Pull request by bimkos**
FIX PROXY

### CODE REVIEW

**Comment by bimkos** [comment]
Something I messed up with the commits. Tell me if there are any problems, I will delete the request. Sorry

**Comment by Mzack9999** [comment]
@bimkos - Thanks for the PR! I anyway think that current naming (`HttpProxy`)  is more appropriate. Do you think it's somehow confusing?

**Comment by bimkos** [comment]
I think that HttpProxy can be a bit confusing since, in fact, you can use any proxy (socks5, HTTP, etc.).

**Comment by bauthard** [comment]
Hi @bimkos, 

Thank you for the feedback, but as this is something already in use and published already, we should keep it as is it, as such closing this PR, thank you again.

**Pull request closed without merging**
