### PR TITLE
Adding Screenshot support

### PR DESCRIPTION
**Pull request by Mzack9999**
## Description
This PR adds basic support for headless mode by adding two new flags:
- `-screenshot` enables headless mode to take screenshots
- `-system-chrome` uses the local installed chrome if any

When the screenshot flag is used, also the rendered dom is retrieved and added to the json output under `headless_body`. The screenshot image is saved in the store response folder and an index file called `index_screenshot.txt` is created.

Doc - https://github.com/projectdiscovery/httpx/tree/issue-385-screenshot#screenshot

```console
$ git clone https://github.com/projectdiscovery/httpx.git; cd httpx/cmd/httpx/
$ git checkout issue-385-screenshot
$ go build
$ echo www.projectdiscovery.io | ./httpx -screenshot
    __    __  __       _  __
   / /_  / /_/ /_____ | |/ /
  / __ \/ __/ __/ __ \|   /
 / / / / /_/ /_/ /_/ /   |
/_/ /_/\__/\__/ .___/_/|_|
             /_/

		projectdiscovery.io

[INF] Current httpx version v1.2.9 (latest)
https://www.projectdiscovery.io
```

```
tree output/
output/
├── response
│   ├── index.txt
│   └── www.projectdiscovery.io
│       └── 89dbec3c06cdc2f6e4586907775aecb0e2520783.txt
└── screenshot
    ├── index_screenshot.txt
    └── www.projectdiscovery.io
        └── 89dbec3c06cdc2f6e4586907775aecb0e2520783.png

6 directories, 4 files

```

89dbec3c06cdc2f6e4586907775aecb0e2520783

### CODE REVIEW

**Comment by Mzack9999** [comment]
- [ ] Hanging zombie chromium processes on windows

**Comment by Mzack9999** [comment]
Depends on https://github.com/projectdiscovery/utils/pull/137

**Review by tarunKoyalwar — APPROVED** [review]
lgtm !

Q: when using `-screenshot` httpx stores response dump to `responses` even if `-store-response` is not used . Is this expected ?

**Comment by Mzack9999** [comment]
@tarunKoyalwar yeah I thought it could make sense to also store the response, as while taking screenshot we also retrieve the rendered DOM. What do you think @ehsandeep should we keep things separated?

**Comment by ehsandeep** [comment]
> @tarunKoyalwar yeah I thought it could make sense to also store the response, as while taking screenshot we also retrieve the rendered DOM. What do you think @ehsandeep should we keep things separated?

we can keep the current behavior as it is since the response information can be used to associate with the screenshot information.

**Review by ehsandeep — APPROVED** [review]

**Comment by ulises2k** [comment]
BUG:
image

image
image

**Pull request merged**
